ci: fix arm64
Signed-off-by: Jack Yu <jack.yu@suse.com>

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,10 +1,16 @@
 FROM registry.suse.com/bci/bci-base:15.5
 
+ARG TARGETPLATFORM
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+
 RUN zypper -n rm container-suseconnect && \
     zypper -n install zip curl which tar && \
     zypper -n clean -a && rm -rf /tmp/* /var/tmp/* /usr/share/doc/packages/*
 
-ARG ARCH=amd64
+ENV ARCH=${TARGETPLATFORM#linux/}
 ENV TINI_VERSION v0.19.0
 ENV TINI_URL_amd64=https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini \
     TINI_URL_arm64=https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-arm64 \
@@ -20,7 +26,7 @@ RUN chmod +x /usr/bin/entrypoint.sh
 ADD hack/support-bundle-collector.sh /usr/bin
 RUN chmod +x /usr/bin/support-bundle-collector.sh
 
-ADD bin/support-bundle-kit /usr/bin
+ADD bin/support-bundle-kit-${ARCH} /usr/bin/support-bundle-kit
 RUN chmod +x /usr/bin/support-bundle-kit
 
 ADD hack/collector-* /usr/bin/
